apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-spring-kotlin
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: app
    repoURL: 'https://github.com/kishorprabhat/tekton-practice.git'
    targetRevision: HEAD
  project: default
